# Generated by Django 5.1.4 on 2025-01-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_user_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Essay',
        ),
        migrations.DeleteModel(
            name='GkChatbot',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='Punctuation',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
