# Generated by Django 5.0.6 on 2025-08-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_remove_userdata_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
