# Generated by Django 5.1.4 on 2025-01-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('contact_no', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('essay_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'essay',
            },
        ),
        migrations.CreateModel(
            name='GkChatbot',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gk_chatbot',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homework_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='Punctuation',
            fields=[
                ('correction_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('original_text', models.TextField()),
                ('corrected_text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'punctuation',
            },
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
    ]
