# Generated by Django 5.1.4 on 2025-01-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_user_created_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
