# Generated by Django 5.1.4 on 2025-01-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpassword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
