# Generated by Django 5.1.4 on 2025-01-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_userdata_delete_admin_delete_essay_delete_gkchatbot_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='User',
        ),
    ]
