# Generated by Django 5.1.4 on 2025-01-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_userdata_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='created_at',
        ),
    ]
